// Supabase Configuration
// This file is automatically generated when connecting to Supabase project
// Project ID: jazutrbrovcqdlibwppz

class SupabaseConfig {
  static const String supabaseUrl = 'https://jazutrbrovcqdlibwppz.supabase.co';
  static const String supabaseAnonKey = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphenV0cmJyb3ZjcWRsaWJ3cHB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1NDcyNzcsImV4cCI6MjA3ODEyMzI3N30.VmH221dquPCjtM_jIz4FbJfnLwooFcATSyo8Nd_m7FY';
}
